function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#proxy_loading", "load")
end


function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "init")
		msg.post(sender, "enable")
	elseif message_id == hash("unload_proxy") then
		msg.post(message.proxy, "unload")
	elseif message_id == hash("load_proxy") then
		msg.post(message.proxy, "load")
	end
end